version: '3.8'

services:
  victim:
    image: alpine:latest
    container_name: victim
    hostname: victim
    networks:
      suricata-lab:
        ipv4_address: 172.16.90.10
    command: sh -c "apk add --no-cache python3 && python3 -m http.server 8000"

  attacker:
    image: kalilinux/kali-rolling:latest
    container_name: attacker
    hostname: attacker
    networks:
      suricata-lab:
        ipv4_address: 172.16.90.20
    command: tail -f /dev/null

networks:
  suricata-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.90.0/24
