services:
  attacker:
    image: kalilinux/kali-rolling:latest
    container_name: attacker
    hostname: attacker
    networks:
      vulnnet:
        ipv4_address: 172.20.0.10
    stdin_open: true
    tty: true
    command: /bin/bash

  victim-activemq:
    image: vulhub/activemq:5.16.5
    container_name: victim-activemq
    hostname: victim-activemq
    networks:
      vulnnet:
        ipv4_address: 172.20.0.101
    ports:
      - "61616:61616"
      - "8161:8161"

  victim-redis:
    image: redis:5.0.7
    container_name: victim-redis
    hostname: victim-redis
    networks:
      vulnnet:
        ipv4_address: 172.20.0.102
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --protected-mode no --save ""

  victim-minio-node1:
    image: vulhub/minio:2023-02-27T18-10-45Z
    container_name: victim-minio-node1
    hostname: victim-minio-node1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin-vulhub
    networks:
      vulnnet:
        ipv4_address: 172.20.0.103
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - minio
      - server
      - --console-address
      - :9001
      - http://victim-minio-node1:9000/mnt/data1
      - http://victim-minio-node2:9000/mnt/data2
      - http://victim-minio-node3:9000/mnt/data3
    volumes:
      - minio_data1:/mnt/data1

  victim-minio-node2:
    image: vulhub/minio:2023-02-27T18-10-45Z
    container_name: victim-minio-node2
    hostname: victim-minio-node2
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin-vulhub
    networks:
      vulnnet:
        ipv4_address: 172.20.0.113
    command:
      - minio
      - server
      - http://victim-minio-node1:9000/mnt/data1
      - http://victim-minio-node2:9000/mnt/data2
      - http://victim-minio-node3:9000/mnt/data3
    volumes:
      - minio_data2:/mnt/data2

  victim-minio-node3:
    image: vulhub/minio:2023-02-27T18-10-45Z
    container_name: victim-minio-node3
    hostname: victim-minio-node3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin-vulhub
    networks:
      vulnnet:
        ipv4_address: 172.20.0.114
    command:
      - minio
      - server
      - http://victim-minio-node1:9000/mnt/data1
      - http://victim-minio-node2:9000/mnt/data2
      - http://victim-minio-node3:9000/mnt/data3
    volumes:
      - minio_data3:/mnt/data3

  victim-samba:
    image: vulhub/samba:4.6.3
    container_name: victim-samba
    hostname: victim-samba
    networks:
      vulnnet:
        ipv4_address: 172.20.0.104
    ports:
      - "445:445"
      - "6699:6699"
    volumes:
      - ./smb.conf:/etc/samba/smb.conf:ro
    tty: true

  victim-jenkins:
    image: vulhub/jenkins:2.441
    container_name: victim-jenkins
    hostname: victim-jenkins
    networks:
      vulnnet:
        ipv4_address: 172.20.0.105
    ports:
      - "8080:8080"
      - "50000:50000"
      - "5005:5005"
    init: true
    environment:
      - DEBUG=1

  evebox:
    image: jasonish/evebox:latest
    container_name: evebox
    hostname: evebox
    networks:
      vulnnet:
        ipv4_address: 172.20.0.200
    ports:
      - "5636:5636"
    volumes:
      - /var/log/suricata/eve.json:/var/log/suricata/eve.json:ro
    command: -e /var/log/suricata/eve.json

volumes:
  minio_data1:
  minio_data2:
  minio_data3:

networks:
  vulnnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16


